#!/bin/bash

# Get salt repo key
wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -

# Add salt repo 
sudo echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list

# apt update
sudo apt-get update

# Install salt minion
sudo apt-get -y install salt-master

# Salt master config
cat <<'EOF' >> /etc/salt/master
file_roots:
    base:
        - /srv/salt
EOF

# Salt master service restart
sudo /etc/init.d/salt-master restart

# Git clone to salt /srv
#git clone http://54.71.64.51/root/sample.git /tmp/sample/
#cp -ar /tmp/sample/saltstack/step2/* /srv/

# Salt master config
cat <<'EOF' >> /root/salt_script.sh
salt '*' grains.append roles influxdb
salt '*' grains.append roles kapacitor
salt '*' grains.append roles grafana
salt '*' state.apply pillar='{"channel":"monitoring"}'
EOF